name: Build pages

on: [push, workflow_dispatch]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:

  json-yaml-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate YAML files
        uses: cardinalby/schema-validator-action@v3
        with:
          file: data/*.y*ml
          schema: data.schema.yml

  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ecosystem-map  
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
      # Lint and Build
      - run: npm run lint && npm run stylelint
      - run: npm run build
      # Populate with data
      - run: cp ../img/* dist/img/
      - run: node --experimental-specifier-resolution=node --loader ts-node/esm src/utils/combineYAMLs.ts ../data/ > dist/projects.json
      - name: Upload artifact
        id: upload-artifact
        uses: actions/upload-pages-artifact@v3.0.1
        if: github.ref == 'refs/heads/main'
        with:
          name: github-pages
          path: ecosystem-map/dist
          if-no-files-found: error

  deploy:
    if: github.ref == 'refs/heads/main'
    needs:
      - build
      - json-yaml-validate

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
      
